# Generated by Django 5.2 on 2025-04-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('data_rate', models.FloatField(default=0)),
                ('latency', models.IntegerField(default=0)),
                ('status', models.CharField(default='Online', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('altitude', models.FloatField(default=0)),
                ('velocity', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cpu_usage', models.FloatField(default=0)),
                ('memory_usage', models.FloatField(default=0)),
                ('cpu_temperature', models.FloatField(default=0)),
                ('memory_temperature', models.FloatField(default=0)),
                ('uptime', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('payload_type', models.CharField(default='Camera', max_length=50)),
                ('compression_rate', models.FloatField(default=0)),
                ('value', models.FloatField(default=0)),
                ('memory_size', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('battery_level', models.FloatField(default=0)),
                ('battery_voltage', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('sensor_telemetry', models.BooleanField(default=True)),
                ('sensor_gps', models.BooleanField(default=True)),
                ('sensor_communication', models.BooleanField(default=True)),
                ('sensor_thermal', models.BooleanField(default=True)),
                ('sensor_payload', models.BooleanField(default=True)),
                ('sensor_control', models.BooleanField(default=True)),
                ('sensor_obc', models.BooleanField(default=True)),
                ('sensor_power', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thermal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('internal_temperature', models.FloatField(default=0)),
                ('external_temperature', models.FloatField(default=0)),
                ('battery_temperature', models.FloatField(default=0)),
                ('cooling_status', models.CharField(default='Active', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
